title: Tom TKG's Homepage
description: The site owner is an IT researcher.　You can see his papers, codes, and images on this site.
url: "https://tomtkg.github.io"
#baseurl: "./"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: UA-170789008-1

plugins:
 - jekyll-sitemap
 - jekyll-seo-tag

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "index"
 - name: "Download"
   link: "download"
 - name: "Image"
   link: "image"
