title: Tom TKG's Homepage
author: Tomoaki Takagi
url: "https://tomtkg.github.io"
#baseurl: "./"

highlighter: rouge
kramdown:
  math_engine: mathjax # katexと書いてもGithubPagesはmathjaxに上書きする
  syntax_highlighter: rouge

tracking_id: UA-170789008-1

plugins:
 - jekyll-sitemap
 - jekyll-seo-tag

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "index"
 - name: "研究"
   link: "researchJP"
 - name: "Image"
   link: "image"
 - name: "Animation"
   link: "animation"
 - name: "Lecture"
   link: "lecture"
 - name: "Paper"
   link: "paper"
 - name: "論文"
   link: "paperJP"
 - name: "参考"
   link: "bib"
 - name: "雑記"
   link: "memo"
